services:
  local-lambda:
    build: .
    platform: linux/amd64
    develop:
      watch:
        - action: rebuild
          path: src/ 
          target: /var/task # this is is the ${LAMBDA_TASK_ROOT} directory
    ports:
      - "9000:8080"
